import * as React from 'react';
import PropTypes from 'prop-types';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

import img3 from '../../../assets/palm-with-pool.jpg'
import './Season.css'

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

export default function Season() {
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <Box sx={{ width: '100%' }}>
      <Box sx={{ borderBottom: 1, borderColor: 'divider', paddingLeft: 10 }}>
        <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
          <Tab label="Spring" {...a11yProps(0)} />
          <Tab label="Summer" {...a11yProps(1)} />
          <Tab label="Autumn" {...a11yProps(2)} />
          <Tab label="Winter" {...a11yProps(3)} />
        </Tabs>
      </Box>
      <TabPanel value={value} index={0}>

            <div className="season-cards">
              <div className='season-card'>
                <p className='season-title'>Spring</p>
                <p className='season-text'>
                The oasis of Figuig presents itself as a coherent,
                material and cultural whole, where there is a
                  complementarity between the architecture and 
                  the spatial organization of ksour, the palm grove 
                  and its irrigation system and all social and 
                  cultural practices. This configuration is accentuated
                  by its enclavement situation, generated by 
                  the closure of the Algerian border.
                </p>
              </div>

              <div  className="season-img">
                <img
                src={img3}
                alt=""             
                />
              </div>
            </div>
    
      </TabPanel>
      <TabPanel value={value} index={1}>
      <div className="season-cards">
              <div className='season-card'>
                <p className='season-title'>Summer</p>
                <p className='season-text'>
                The oasis of Figuig presents itself as a coherent,
                material and cultural whole, where there is a
                  complementarity between the architecture and 
                  the spatial organization of ksour, the palm grove 
                  and its irrigation system and all social and 
                  cultural practices. This configuration is accentuated
                  by its enclavement situation, generated by 
                  the closure of the Algerian border.
                </p>
              </div>

              <div  className="season-img">
                <img
                src={img3}
                alt=""             
                />
              </div>
            </div>
      </TabPanel>
      <TabPanel value={value} index={2}>
      <div className="season-cards">
              <div className='season-card'>
                <p className='season-title'>Autumn</p>
                <p className='season-text'>
                The oasis of Figuig presents itself as a coherent,
                material and cultural whole, where there is a
                  complementarity between the architecture and 
                  the spatial organization of ksour, the palm grove 
                  and its irrigation system and all social and 
                  cultural practices. This configuration is accentuated
                  by its enclavement situation, generated by 
                  the closure of the Algerian border.
                </p>
              </div>

              <div  className="season-img">
                <img
                src={img3}
                alt=""             
                />
              </div>
            </div>
      </TabPanel>
      <TabPanel value={value} index={3}>
      <div className="season-cards">
              <div className='season-card'>
                <p className='season-title'>Winter</p>
                <p className='season-text'>
                The oasis of Figuig presents itself as a coherent,
                material and cultural whole, where there is a
                  complementarity between the architecture and 
                  the spatial organization of ksour, the palm grove 
                  and its irrigation system and all social and 
                  cultural practices. This configuration is accentuated
                  by its enclavement situation, generated by 
                  the closure of the Algerian border.
                </p>
              </div>

              <div  className="season-img">
                <img
                src={img3}
                alt=""             
                />
              </div>
            </div>
      </TabPanel>
    </Box>
  );
}