import React from 'react'
import Navbar from '../navbar/Navbar'
import img1 from '../../assets/plane.png'
import img2 from '../../assets/food-msemen.jpg'
import img3 from '../../assets/palm-with-pool.jpg'

import Season from './Season/Season'
import Currency from './Currency/Currency'

import './About.css'

const About = () => {

  return (
    <>
    <div className='About-section'>
      <div className='nav'>
        <Navbar />
      </div>
      
      <img
        src={img1}
        alt=""
        className="about-img"
      />

      <h1 className='About-title'>About FIGUIG</h1>

    </div>

      <div className='about-content'>

        <h1 className='content-title'>Traditions of Figuig</h1>

        <div className='content-box'>

          <div className="box-one">
            <div  className="content-img">
              <img
              src={img2}
              alt=""
             
              />
            </div>

            <div className='about-texts'>
              <p className='text-title'>Language</p>
              <p className='first-text'>
                Arabic is the official language of Morocco<br></br>
                 and the primary language used in all dealings <br></br>
                 in Figuig is TAMAZIGHT.
              </p>
            </div>
          </div>

          <div className="box-two">
            <div className='about-texts2'>
                <p className='text-title'>Culture</p>
                <p className='first-text'>
                The oasis of Figuig presents itself as a coherent,
                material and cultural whole, where there is a
                  complementarity between the architecture and 
                  the spatial organization of ksour, the palm grove 
                  and its irrigation system and all social and 
                  cultural practices. This configuration is accentuated
                  by its enclavement situation, generated by 
                  the closure of the Algerian border.
                </p>
              </div>

              <div  className="content-img">
                <img
                src={img2}
                alt=""           
                />

              </div>
            
          </div>
            
        </div>

      </div>

      <div className="seasons">
        <h1 className='season-title'>Climate & Seasons</h1>

        <Season />

        <Currency />

      </div>

      </>
    
    
  )
}

export default About
